import type { Category, ComboItem, Product, Store } from "./types";

// 강서구 대략 중심점 (내 위치 목업)
export const MY_LOCATION = { lat: 37.5509, lng: 126.8495 };

export const CATEGORY_LABEL: Record<Category, string> = {
  riceball: "삼각김밥",
  lunchbox: "도시락",
  sandwich: "샌드위치",
  drink: "음료",
  snack: "간식",
};

export const CATEGORY_EMOJI: Record<Category, string> = {
  riceball: "🍙",
  lunchbox: "🍱",
  sandwich: "🥪",
  drink: "🥤",
  snack: "🍿",
};

export const STORES: Store[] = [
  {
    id: "r1",
    type: "restaurant",
    name: "뚜벅이분식",
    lat: 37.5522,
    lng: 126.8503,
    address: "서울 강서구 등촌로 12",
    phone: "02-123-4567",
    hours: "09:00 - 21:00",
  },
  {
    id: "r2",
    type: "restaurant",
    name: "등촌동김밥천국",
    lat: 37.5567,
    lng: 126.8551,
    address: "서울 강서구 등촌로 45",
    phone: "02-234-5678",
    hours: "07:00 - 22:00",
  },
  {
    id: "r3",
    type: "restaurant",
    name: "화곡동맛있는떡볶이",
    lat: 37.5417,
    lng: 126.8402,
    address: "서울 강서구 화곡로 88",
    phone: "02-345-6789",
    hours: "10:00 - 20:00",
    closed: true,
  },
  {
    id: "r4",
    type: "restaurant",
    name: "마곡동설렁탕집",
    lat: 37.5606,
    lng: 126.8265,
    address: "서울 강서구 마곡중앙로 3",
    phone: "02-456-7890",
    hours: "08:00 - 21:00",
  },
  {
    id: "r5",
    type: "restaurant",
    name: "강서네분식",
    lat: 37.5488,
    lng: 126.839,
    address: "서울 강서구 강서로 21",
    phone: "02-567-8901",
    hours: "10:00 - 20:30",
  },
  {
    id: "c1",
    type: "convenience",
    name: "CU 등촌점",
    lat: 37.5545,
    lng: 126.853,
    address: "서울 강서구 등촌로 30",
    phone: "02-678-9012",
    hours: "24시간",
  },
  {
    id: "c2",
    type: "convenience",
    name: "GS25 화곡역점",
    lat: 37.5405,
    lng: 126.841,
    address: "서울 강서구 화곡로 100",
    phone: "02-789-0123",
    hours: "24시간",
  },
  {
    id: "c3",
    type: "convenience",
    name: "세븐일레븐 마곡점",
    lat: 37.5599,
    lng: 126.829,
    address: "서울 강서구 마곡중앙로 15",
    phone: "02-890-1234",
    hours: "24시간",
  },
  {
    id: "c4",
    type: "convenience",
    name: "CU 강서구청점",
    lat: 37.5509,
    lng: 126.8495,
    address: "서울 강서구 화곡로 302",
    phone: "02-901-2345",
    hours: "24시간",
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    storeType: "convenience",
    category: "riceball",
    name: "참치마요 삼각김밥",
    emoji: "🍙",
    energyKcal: 180,
    carbG: 30,
    proteinG: 4,
    fatG: 6,
    sodiumMg: 380,
    veggieLevel: 1,
  },
  {
    id: "p2",
    storeType: "convenience",
    category: "riceball",
    name: "전주비빔 삼각김밥",
    emoji: "🍙",
    energyKcal: 170,
    carbG: 32,
    proteinG: 4,
    fatG: 3,
    sodiumMg: 420,
    veggieLevel: 2,
  },
  {
    id: "p3",
    storeType: "convenience",
    category: "lunchbox",
    name: "제육볶음 도시락",
    emoji: "🍱",
    energyKcal: 650,
    carbG: 85,
    proteinG: 22,
    fatG: 18,
    sodiumMg: 950,
    veggieLevel: 2,
  },
  {
    id: "p4",
    storeType: "convenience",
    category: "lunchbox",
    name: "치킨가라아게 도시락",
    emoji: "🍱",
    energyKcal: 720,
    carbG: 78,
    proteinG: 25,
    fatG: 26,
    sodiumMg: 1100,
    veggieLevel: 1,
  },
  {
    id: "p5",
    storeType: "convenience",
    category: "sandwich",
    name: "에그마요 샌드위치",
    emoji: "🥪",
    energyKcal: 310,
    carbG: 34,
    proteinG: 11,
    fatG: 13,
    sodiumMg: 480,
    veggieLevel: 2,
  },
  {
    id: "p6",
    storeType: "convenience",
    category: "sandwich",
    name: "햄치즈 샌드위치",
    emoji: "🥪",
    energyKcal: 340,
    carbG: 36,
    proteinG: 13,
    fatG: 15,
    sodiumMg: 690,
    veggieLevel: 2,
  },
  {
    id: "p7",
    storeType: "convenience",
    category: "drink",
    name: "흰우유 200ml",
    emoji: "🥛",
    energyKcal: 130,
    carbG: 10,
    proteinG: 6,
    fatG: 7,
    sodiumMg: 100,
    veggieLevel: 1,
  },
  {
    id: "p8",
    storeType: "convenience",
    category: "drink",
    name: "탄산음료 500ml",
    emoji: "🥤",
    energyKcal: 225,
    carbG: 57,
    proteinG: 0,
    fatG: 0,
    sodiumMg: 35,
    veggieLevel: 1,
  },
  {
    id: "p9",
    storeType: "convenience",
    category: "snack",
    name: "구운계란 2입",
    emoji: "🥚",
    energyKcal: 140,
    carbG: 1,
    proteinG: 12,
    fatG: 10,
    sodiumMg: 220,
    veggieLevel: 1,
  },
  {
    id: "p10",
    storeType: "convenience",
    category: "snack",
    name: "감자칩 한 봉",
    emoji: "🍟",
    energyKcal: 300,
    carbG: 33,
    proteinG: 3,
    fatG: 18,
    sodiumMg: 380,
    veggieLevel: 1,
  },
];

// 조합 추천용 보완 상품 (단백질 낮을 때 함께 안내)
export const COMBO_ITEMS: ComboItem[] = [
  { id: "combo-egg", name: "계란", emoji: "🥚" },
  { id: "combo-milk", name: "우유", emoji: "🥛" },
  { id: "combo-soymilk", name: "두유", emoji: "🧃" },
];

export function getProductsByCategory(category: Category): Product[] {
  return PRODUCTS.filter((p) => p.category === category);
}

export function getStoreById(id: string): Store | undefined {
  return STORES.find((s) => s.id === id);
}

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}
